export interface TuViConGiap {
  chi: string;
  name: string;
  hanh: string;
  menh: string;
  overview: string;
  career: string;
  wealth: string;
  love: string;
  health: string;
  luckyNumber: number[];
  luckyColor: string[];
  quyNhan: string[];
}

export const TU_VI_12_CON_GIAP: Record<string, TuViConGiap> = {
  'Tý': {
    chi: 'Tý',
    name: 'Tuổi Tý (Chuột)',
    hanh: 'Thủy',
    menh: 'Dương Thủy',
    overview: 'Người tuổi Tý thông minh, lanh lợi, thích nghi nhanh với mọi hoàn cảnh. Năm nay vận trình có nhiều khởi sắc, cần nắm bắt cơ hội kinh doanh và mở rộng quan hệ.',
    career: 'Công việc hanh thông, có quý nhân phù trợ. Phù hợp khởi sự dự án mới hoặc đề xuất tăng lương thăng chức.',
    wealth: 'Tài chính dồi dào, thu nhập chính và phụ đều gia tăng. Nên tích lũy thay vì đầu tư mạo hiểm.',
    love: 'Tình duyên êm ấm, người độc thân có cơ hội gặp ý trung nhân qua bạn bè giới thiệu.',
    health: 'Chú ý các bệnh về tiêu hóa và giấc ngủ. Tránh thức khuya và làm việc quá sức.',
    luckyNumber: [1, 6, 8],
    luckyColor: ['Xanh lam', 'Đen', 'Trắng'],
    quyNhan: ['Thìn', 'Thân', 'Sửu'],
  },
  'Sửu': {
    chi: 'Sửu',
    name: 'Tuổi Sửu (Trâu)',
    hanh: 'Thổ',
    menh: 'Âm Thổ',
    overview: 'Người tuổi Sửu chăm chỉ, kiên nhẫn, điềm đạm và đáng tin cậy. Năm nay vận khí ổn định, nỗ lực bền bỉ sẽ đem lại thành quả xứng đáng.',
    career: 'Tiến triển từng bước vững chắc. Hãy kiên trì với mục tiêu đã định, tránh thay đổi đột ngột.',
    wealth: 'Thu nhập ổn định từ công việc chính. Cần kiểm soát chi tiêu gia đình hợp lý.',
    love: 'Gia đạo yên vui, vợ chồng hòa thuận thấu hiểu. Người độc thân nên mở lòng hơn.',
    health: 'Thể lực tốt, duy trì luyện tập thể thao đều đặn để nâng cao sức đề kháng.',
    luckyNumber: [2, 5, 9],
    luckyColor: ['Vàng', 'Nâu đất', 'Đỏ'],
    quyNhan: ['Tý', 'Tỵ', 'Dậu'],
  },
  'Dần': {
    chi: 'Dần',
    name: 'Tuổi Dần (Hổ)',
    hanh: 'Mộc',
    menh: 'Dương Mộc',
    overview: 'Người tuổi Dần quyết đoán, can đảm, có tố chất lãnh đạo tiên phong. Thời gian tới gặp nhiều thời cơ lớn để khẳng định vị thế cá nhân.',
    career: 'Được cấp trên tin tưởng giao trọng trách. Cần giữ bình tĩnh, tránh nóng vội trong đàm phán.',
    wealth: 'Tài vận rực rỡ, kinh doanh buôn bán thu lợi lớn. Chú ý giữ uy tín trong giao dịch.',
    love: 'Cần dành thêm thời gian quan tâm nửa kia, tránh để công việc chiếm hết thời gian.',
    health: 'Cẩn thận khi tham gia giao thông và các hoạt động thể thao cường độ cao.',
    luckyNumber: [3, 7, 8],
    luckyColor: ['Xanh lá', 'Xanh lục', 'Xanh đen'],
    quyNhan: ['Ngọ', 'Tuất', 'Hợi'],
  },
  'Mão': {
    chi: 'Mão',
    name: 'Tuổi Mão (Mèo)',
    hanh: 'Mộc',
    menh: 'Âm Mộc',
    overview: 'Người tuổi Mão khéo léo, tinh tế, giàu lòng nhân ái. Vận trình thuận hòa, đời sống tinh thần phong phú và bình an.',
    career: 'Môi trường làm việc thân thiện, đồng nghiệp ủng hộ. Phù hợp các công việc sáng tạo, nghệ thuật.',
    wealth: 'Tiền bạc chi tiêu vừa phải, có khoản tích lũy an toàn. Không nên cho vay mượn tùy tiện.',
    love: 'Đào hoa nở rộ, tình cảm lãng mạn ngọt ngào. Nhiều cặp đôi tính chuyện trăm năm.',
    health: 'Sức khỏe dồi dào, nên bổ sung rau xanh và duy trì thói quen uống đủ nước.',
    luckyNumber: [4, 6, 9],
    luckyColor: ['Hồng', 'Tím', 'Xanh ngọc'],
    quyNhan: ['Hợi', 'Mùi', 'Tuất'],
  },
  'Thìn': {
    chi: 'Thìn',
    name: 'Tuổi Thìn (Rồng)',
    hanh: 'Thổ',
    menh: 'Dương Thổ',
    overview: 'Người tuổi Thìn khí khái, tài hoa, có chí lớn. Vận trình đại cát đại lợi, dễ lập công danh vang dội.',
    career: 'Bứt phá ngoạn mục, nhiều hợp đồng giá trị được ký kết. Uy tín trong ngành tăng cao.',
    wealth: 'Tài lộc cuồn cuộn, nguồn tiền dồi dào. Đầu tư dài hạn có triển vọng sinh lời lớn.',
    love: 'Tình cảm khởi sắc, người độc thân dễ tìm được người tâm đầu ý hợp.',
    health: 'Chú ý ăn uống đúng giờ, hạn chế đồ uống có cồn trong các buổi tiệc tùng.',
    luckyNumber: [1, 7, 8],
    luckyColor: ['Vàng kim', 'Bạc', 'Nâu'],
    quyNhan: ['Tý', 'Thân', 'Dậu'],
  },
  'Tỵ': {
    chi: 'Tỵ',
    name: 'Tuổi Tỵ (Rắn)',
    hanh: 'Hỏa',
    menh: 'Âm Hỏa',
    overview: 'Người tuổi Tỵ sắc sảo, trực giác nhạy bén, mưu trí sâu sắc. Vận trình thuận lợi cho việc học tập, nghiên cứu và tích lũy kiến thức.',
    career: 'Công việc đạt bước tiến tốt, nhiều ý tưởng sáng tạo được khen thưởng.',
    wealth: 'Tài chính cân bằng, biết cách quản lý ngân sách thông minh và hiệu quả.',
    love: 'Thấu hiểu và chia sẻ giúp mối quan hệ thêm bền chặt, gắn kết.',
    health: 'Nên dành thời gian thư giãn tinh thần, thiền hoặc đi dạo để giải tỏa căng thẳng.',
    luckyNumber: [2, 8, 9],
    luckyColor: ['Đỏ', 'Cam', 'Tím'],
    quyNhan: ['Sửu', 'Dậu', 'Thân'],
  },
  'Ngọ': {
    chi: 'Ngọ',
    name: 'Tuổi Ngọ (Ngựa)',
    hanh: 'Hỏa',
    menh: 'Dương Hỏa',
    overview: 'Người tuổi Ngọ năng động, tự do, nhiệt huyết và cởi mở. Năm nay thích hợp cho các chuyến xuất hành, mở rộng thị trường mới.',
    career: 'Nhiều chuyến công tác đem lại cơ hội thăng tiến. Được đối tác đánh giá cao sự chủ động.',
    wealth: 'Tiền vào nhiều nhưng chi cũng không ít. Cần lập kế hoạch tài chính rõ ràng.',
    love: 'Sôi nổi, nhiệt tình trong tình cảm. Cần lắng nghe đối phương nhiều hơn.',
    health: 'Chú ý sức khỏe tim mạch và huyết áp. Tránh thức khuya và làm việc quá độ.',
    luckyNumber: [3, 7, 9],
    luckyColor: ['Đỏ tươi', 'Tím', 'Xanh lục'],
    quyNhan: ['Dần', 'Tuất', 'Mùi'],
  },
  'Mùi': {
    chi: 'Mùi',
    name: 'Tuổi Mùi (Dê)',
    hanh: 'Thổ',
    menh: 'Âm Thổ',
    overview: 'Người tuổi Mùi ôn hòa, nhẫn nại, trọng nghĩa tình. Vận thế bình ổn, cuộc sống sung túc an nhàn.',
    career: 'Công việc tiến triển êm đềm, ít sóng gió. Được cấp trên và đồng nghiệp quý mến.',
    wealth: 'Tài chính vững vàng, có của ăn của để. Thích hợp mua sắm bất động sản hoặc tích sản.',
    love: 'Gia đình là hậu phương vững chắc, con cái ngoan ngoãn hiếu thuận.',
    health: 'Hệ tiêu hóa khỏe mạnh, nên tham gia các môn thể thao nhẹ nhàng như yoga, đi bộ.',
    luckyNumber: [4, 5, 8],
    luckyColor: ['Vàng nhạt', 'Nâu', 'Xanh lam'],
    quyNhan: ['Hợi', 'Mão', 'Ngọ'],
  },
  'Thân': {
    chi: 'Thân',
    name: 'Tuổi Thân (Khỉ)',
    hanh: 'Kim',
    menh: 'Dương Kim',
    overview: 'Người tuổi Thân nhanh trí, hoạt bát, sáng tạo và đa tài. Năm nay gặp nhiều may mắn bất ngờ trong công việc và đầu tư.',
    career: 'Phát huy tối đa năng lực giải quyết vấn đề. Dễ có bước nhảy vọt trong sự nghiệp.',
    wealth: 'Nhiều khoản thu phụ bất ngờ. Tài vận hanh thông, ví tiền rủng rỉnh.',
    love: 'Duyên số đưa đẩy gặp gỡ nhiều người thú vị. Tình cảm thăng hoa viên mãn.',
    health: 'Sức khỏe tốt, tinh thần phấn chấn lạc quan.',
    luckyNumber: [1, 5, 7],
    luckyColor: ['Trắng', 'Xám', 'Vàng kim'],
    quyNhan: ['Tý', 'Thìn', 'Tỵ'],
  },
  'Dậu': {
    chi: 'Dậu',
    name: 'Tuổi Dậu (Gà)',
    hanh: 'Kim',
    menh: 'Âm Kim',
    overview: 'Người tuổi Dậu cẩn trọng, tỉ mỉ, có trách nhiệm cao. Vận trình ổn định, mọi công việc đều đâu vào đấy theo đúng kế hoạch.',
    career: 'Làm việc nguyên tắc, kỷ luật mang lại kết quả xuất sắc. Được đề bạt vị trí cao hơn.',
    wealth: 'Thu nhập tăng trưởng đều đặn. Kế hoạch tiết kiệm đạt mục tiêu sớm hơn dự kiến.',
    love: 'Tình cảm chín muồi, là thời điểm lý tưởng để xây dựng tổ ấm gia đình.',
    health: 'Cần chú ý hệ hô hấp khi chuyển mùa, giữ ấm cơ thể khi thời tiết se lạnh.',
    luckyNumber: [2, 6, 8],
    luckyColor: ['Vàng', 'Trắng sữa', 'Nâu'],
    quyNhan: ['Sửu', 'Thìn', 'Tỵ'],
  },
  'Tuất': {
    chi: 'Tuất',
    name: 'Tuổi Tuất (Chó)',
    hanh: 'Thổ',
    menh: 'Dương Thổ',
    overview: 'Người tuổi Tuất trung thành, thẳng thắn, trọng chữ tín. Năm nay đón nhận nhiều sự giúp đỡ từ quý nhân trong cuộc sống.',
    career: 'Gặp gỡ đối tác uy tín, hợp tác làm ăn cùng có lợi. Công việc có chuyển biến tích cực.',
    wealth: 'Tài lộc khởi sắc, các khoản nợ cũ được giải quyết dứt điểm.',
    love: 'Chung thủy, gắn kết yêu thương. Đời sống gia đình hòa thuận êm ấm.',
    health: 'Thể trạng tốt, nên duy trì chế độ dinh dưỡng cân bằng và ngủ đủ giấc.',
    luckyNumber: [3, 6, 9],
    luckyColor: ['Đỏ', 'Cam', 'Vàng đất'],
    quyNhan: ['Dần', 'Ngọ', 'Mão'],
  },
  'Hợi': {
    chi: 'Hợi',
    name: 'Tuổi Hợi (Lợn)',
    hanh: 'Thủy',
    menh: 'Âm Thủy',
    overview: 'Người tuổi Hợi đôn hậu, bao dung, có số hưởng phúc lộc. Vận khí hanh thông, vạn sự cát tường như ý.',
    career: 'Mọi sự trôi chảy, không có áp lực lớn. Thích hợp mở rộng hợp tác làm ăn.',
    wealth: 'Phúc lộc tràn trề, tiền bạc dư dả. Thường xuyên có lộc ăn uống và quà tặng.',
    love: 'Tình cảm hài hòa, ngọt ngào. Gia đạo bình an, hạnh phúc sum vầy.',
    health: 'Sức khỏe tốt, cần chú ý cân nặng và hạn chế ăn đồ ngọt vào buổi tối.',
    luckyNumber: [1, 4, 8],
    luckyColor: ['Xanh lam', 'Trắng', 'Đen'],
    quyNhan: ['Mão', 'Mùi', 'Dần'],
  },
};
